### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by vlulla** [duckdb/duckdb-ui#21]
Upon reading [The DuckDB Local UI](https://duckdb.org/2025/03/12/duckdb-ui.html) blog post I tried it on my local computer only to receive an initialization error. Specifically the error states: `Failed to resolve app state with user - Error: Binder Error: Catalog "_duckdb_ui" does not exist!` What am i doing wrong?

**Comment by patrickdash** [comment]
Similar bug as well on macOS.

```
❯ duckdb -ui
┌──────────────────────────────────────┐
│                result                │
│               varchar                │
├──────────────────────────────────────┤
│ UI started at http://localhost:4213/ │
└──────────────────────────────────────┘
v1.2.1 8e52ec4395
Enter ".help" for usage hints.
D


❯ duckdb --version
v1.2.1 8e52ec4395
```

<img width="642" alt="Image" src="https://github.com/user-attachments/assets/6b964186-2b1d-4423-a336-63e137e23907" />

**Comment by jraymakers** [comment]
This has been fixed in a very recent update to the extension. Please run `update extensions` or `force install ui` and be sure you have the latest version of the `ui` extension, `963e0e4`.

**Comment by Achintya-Lakshmanan** [comment]
Hey, I've got the same issue, I've got the latest version of duckdb v1.2.1 8e52ec4395 and the latest version of the ui 963e0e4. Am I missing something?

**Comment by jraymakers** [comment]
> Hey, I've got the same issue, I've got the latest version of duckdb v1.2.1 8e52ec4395 and the latest version of the ui [963e0e4](https://github.com/duckdb/duckdb-ui/commit/963e0e4d4c6f84b2536e3258fa204290fb8da93b). Am I missing something?

The originally-reported error can occur if you have two copies of the UI running on the same machine. The most recent version attempts to prevent this with a friendly error message, but that mechanism can be defeated if you use a non-default local port. How are you running the UI? Are you using a non-default local port?

**Comment by Achintya-Lakshmanan** [comment]
Ah! got it. I was accidentally running 2 instances of the UI at the same time, now its fixed. Thanks a lot!

**Comment by Lokesh-Chimakurthi** [comment]
I am still facing this issue. tried both `update extensions` and `force install ui`. I have ui extension version `25ff9b6`. duckdb version: DuckDB v1.2.1 8e52ec4395
gcc-10.2.1 20210130 (Red Hat 10.2.1-11). using non-default port 4219. running in linux.

<img width="591" alt="Image" src="https://github.com/user-attachments/assets/32e32fd6-0962-4980-9d4c-1304545e3375" />
